config-version: 2

name: 'amazon_ads_integration_tests'
version: '0.2.0'

profile: 'integration_tests' 

vars:
  amazon_ads_source:
    amazon_ads_schema: amazon_ads_integration_tests_02
    amazon_ads_ad_group_history_identifier: "ad_group_history_data"
    amazon_ads_ad_group_level_report_identifier: "ad_group_level_report_data"
    amazon_ads_advertised_product_report_identifier: "advertised_product_report_data"
    amazon_ads_campaign_history_identifier: "campaign_history_data"
    amazon_ads_campaign_level_report_identifier: "campaign_level_report_data"
    amazon_ads_portfolio_history_identifier: "portfolio_history_data"
    amazon_ads_product_ad_history_identifier: "product_ad_history_data"
    amazon_ads_profile_identifier: "profile_data"
    amazon_ads_keyword_history_identifier: "keyword_history_data"
    amazon_ads_targeting_keyword_report_identifier: "targeting_keyword_report_data"
    amazon_ads_search_term_ad_keyword_report_identifier: "search_term_ad_keyword_report_data"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  amazon_ads_integration_tests:
    +column_types:
      _fivetran_synced: "timestamp"
      campaign_budget_amount: "float"
      click_through_rate: "float"
      keyword_bid: "float"
        
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']
