#!/bin/bash

# Post-checkout hook to configure and load centralized pipeline (runs after checkout)
set -euo pipefail

echo "Generating centralized pipeline..."

curl -fsSL \
  https://raw.githubusercontent.com/fivetran/dbt_package_automations/feature/centralized-bk/.buildkite/scripts/dynamic_pipeline.sh \
  | ENABLED_WAREHOUSES="postgres snowflake" bash

echo "Centralized pipeline generated."