name: 'changelog poc'
on:
  pull_request:
    types:
      - labeled

jobs:
  changelog-poc:
    if: github.event.label.name == 'changelog:ready'
    uses: fivetran/dbt_package_automations/.github/workflows/changelog-poc.yml@changelog-poc/initial-test
    secrets: inherit
