name: Check merge ready

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, reopened]

jobs:
  check-merge-ready:
    uses: fivetran/dbt_package_automations/.github/workflows/check-merge-ready.yml@docs-generator-status-report
    secrets: inherit
